flags:
  semigroups:
    bytestring-builder: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.0.0
- bytestring-builder-0.10.8.1.0
- persistent-2.6
- persistent-template-2.5.1.6
- semigroups-0.18.2
- yesod-text-markdown-0.1.7
resolver: lts-6.17
